#!/bin/bash

# 2 nodes, 1 cores per node, 1GB memory per node
#PBS -l select=2:ncpus=1:mem=1gb place=scatter

# 1 minute walltime
#PBS -l walltime=00:01:00

# execution queue
#PBS -q short_cpuQ

# specify the output file
#PBS -o output.txt

# specify the error file
#PBS -e error.txt

module load mpich-3.2
# 20 because 2 nodes * 10 cores per node
mpirun.actual -n 2 ./parallel_cc.out "input/medium2.txt" 