#!/bin/bash

# 1 node 2GB memory per node
#PBS -l select=1:ncpus=1:mem=100gb -l place=excl

# 1 minute walltime
#PBS -l walltime=02:00:00

# execution queue
#PBS -q short_cpuQ

# specify the output file
#PBS -o serial_output.txt

# specify the error file
#PBS -e serial_error.txt

./serial_cc.out "/shares/HPC4DataScience/big-graph-0.txt" 